version: "3"
services:
  frontend:
    build: ./frontend
    image: frontend
    environment:
      PORT: 8080
      AUTH_API_ADDRESS: http://authapi:8081
      TODOS_API_ADDRESS: http://todosapi:8082
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - 8080:8080
    depends_on:
      - zipkin
      - authapi
      - todosapi
      - usersapi

  authapi:
    build: ./authapi
    image: authapi
    environment:
      AUTH_API_PORT: 8081
      JWT_SECRET: myfancysecret
      USERS_API_ADDRESS: http://usersapi:8083
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - usersapi

  todosapi:
    build: ./todosapi
    image: todosapi
    environment:
      TODO_API_PORT: 8082
      JWT_SECRET: myfancysecret
      REDIS_HOST: redisqueue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - redisqueue

  usersapi:
    build: ./usersapi
    image: usersapi
    environment:
     SERVER_PORT: 8083
     JWT_SECRET: myfancysecret
     SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
      - zipkin
     
  logmessageprocessor:
    build: ./logmessageprocessor
    image: logmessageprocessor
    environment:
      REDIS_HOST: redisqueue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://zipkin:9411/api/v1/spans
    depends_on:
      - zipkin
      - redisqueue
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  redisqueue:
    image: redis