apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
        - name: authapi
          image: "{{ .Values.authapi.image.repository }}:{{ .Values.authapi.image.tag }}"
          ports:
          - containerPort: {{ .Values.authapi.ports.containerPort }}
          env:
           - name: AUTH_API_PORT
             value: "8081"
           - name: JWT_SECRET
             value: myfancysecret
           - name: USERS_API_ADDRESS
             value: http://usersapi:8083
           - name: ZIPKIN_URL
             value: http://zipkin:9411/api/v2/spans

          resources:
            requests:
              cpu: {{ .Values.authapi.resources.requests.cpu }}
              memory: {{ .Values.authapi.resources.requests.memory }}
            limits:
              cpu: {{ .Values.authapi.resources.limits.cpu }}
              memory: {{ .Values.authapi.resources.limits.memory }}
    
