apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: usersapi
  template:
    metadata:
      labels:
        app: usersapi
    spec:
      containers:
        - name: usersapi
          image: "{{ .Values.usersapi.image.repository }}:{{ .Values.usersapi.image.tag }}"
          ports:
          - containerPort: {{ .Values.usersapi.ports.containerPort }}
          env:
          - name: JWT_SECRET
            value: myfancysecret
          - name: SERVER_PORT
            value: "8083"
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin:9411
          resources:
            requests:
              cpu: {{ .Values.usersapi.resources.requests.cpu }}
              memory: {{ .Values.usersapi.resources.requests.memory }}
            limits:
              cpu: {{ .Values.usersapi.resources.limits.cpu }}
              memory: {{ .Values.usersapi.resources.limits.memory }}
    
