apiVersion: v1
kind: Service
metadata:
  name: usersapi
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.usersapi.service.type }}
  selector:
    app: usersapi
  ports:
  - name: {{ .Values.usersapi.service.name }}
    port: {{ .Values.usersapi.service.port }}
    targetPort: {{ .Values.usersapi.ports.containerPort }}
