apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}"
          ports:
          - containerPort: {{ .Values.zipkin.ports.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.zipkin.resources.requests.cpu }}
              memory: {{ .Values.zipkin.resources.requests.memory }}
            limits:
              cpu: {{ .Values.zipkin.resources.limits.cpu }}
              memory: {{ .Values.zipkin.resources.limits.memory }}
    
