apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.zipkin.service.type }}
  selector:
    app: zipkin
  ports:
  - name: {{ .Values.zipkin.service.name }}
    port: {{ .Values.zipkin.service.port }}
    targetPort: {{ .Values.zipkin.ports.containerPort }}
